AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - kuanto-renta::kuanto-renta
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  KuantoRentaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: provided
      CodeUri: build/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        CalculateRenta:
          Type: Api
          Properties:
            Path: /kuantorenta
            Method: POST



Outputs:
  KuantoRentaApi:
    Description: URL for application
    Value: !Sub 'https://${KuantoRentaFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/kuantorenta'
    Export:
      Name: KuantoRentaApi
